ANIMALS = [
    'Spectacled Bear',
    'White Fronted Capuchin',
    'Woolly Monkey',
    'Blue Monkey',
    'Crab Eating Monkey',
    'Spectacled Leaf Monkey',
    'Hanuman Langur',
    'Red Shanked Douc Langur',
    'Concolor Gibbon',
    'Gray Gibbon',
    'European Beaver',
    'Olive Baboon',
    'Addax',
    'Dusky Titi',
    'Guinea Baboon',
    'Giant Anteater',
    'Red Tailed Guenon',
    'American Badger',
    'Common Wombat',
    'White Bellied Spider Monkey',
    'Rhesus Macaque',
    'Ring Tailed Lemur',
    'Potto',
    'Seladang',
    'Honey Badger',
    'Slow Loris',
    'Black Mangabey',
    'Sooty Mangabey',
    'Bald Uakari',
    'Common Squirrel Monkey',
    'Collared Mangabey',
    'Owl Faced Monkey',
    'Japanese Macaque',
    'Gelada',
    'Pig Tailed Macaque',
    'Black Lemur',
    'Old World Porcupine',
    'Western Black and White Colobus',
    'Chacma Baboon',
    'Talapoin',
    'Yellow Baboon',
    'Two Toed Sloth',
    'Mongoose Lemur',
    'Asian Water Buffalo',
    'Giraffe',
    'African Civet',
    'Agile Gibbon',
    'Ruffed Lemur',
    'Caribbean Manatee',
    'Guanaco',
    'Drill',
    'Hamadryas Baboon',
    'Toque Macaque',
    'African Buffalo',
    'Okapi',
    'Giant Panda',
    'African Lion',
    'Sloth Bear',
    'Bottle Nosed Dolphin',
    'Little Brown Bat',
    'California Sea Lion',
    'Diana Monkey',
    'Long Nosed Echidna',
    'Brown Lemur',
    'Capped Gibbon',
    'Silvered Langur',
    'Flying Fox',
    'Lar Gibbon',
    'Vervet',
    'Mandrill',
    'Bobcat',
    'Sumatran Rhinoceros',
    'Gray Cheeked Mangabey',
    'Asiatic Black Bear',
    'Spider Monkey',
    'Guenon',
    'European Genet',
    'Black Spider Monkey',
    'Gibbon Hybrid',
    'Brazilian Tapir',
    'Pygmy Chimpanzee',
    'Lowland Gorilla',
    'Siamang',
    'Crab Eating Macaque',
    'Lion Tailed Macaque',
    'Polar Bear',
    'Onager',
    'Captive Hybrid Lemur',
    'Gorilla',
    'Bison',
    'Hippopotamus',
    'Spotted Hyena',
    'Brown Capuchin',
    'Weeper Capuchin',
    'Gray Seal',
    'Pygmy Hippopotamus',
    'Capuchin',
    'Black Rhinoceros',
    'Grizzly Bear',
    'African Wild Ass',
    'Greater Indian Rhinoceros',
    'Short Nosed Echidna',
    'Camel',
    'Horse',
    'Orangutan',
    'Chimpanzee',
    'Asian Elephant',
    'African Elephant',
    'Hexactinellid Sponge',
    'Bristlecone Pine',
    'Epibenthic Sponge',
    'Common Ginkgo',
    'Umbrella Thorn',
    'Quahog Clam',
    'Greenland Shark',
    'Escarpia Laminata',
    'Seepiophila Jonesi',
    'Lamellibrachia Luymesi',
    'Bowhead Whale',
    'Rougheye Rockfish',
    'Red Sea Urchin',
    'Galapagos Tortoise',
    'Pacific Geoduck',
    'Shortraker Rockfish',
    'Lake Sturgeon',
    'Aldabra Tortoise',
    'Orange Roughy',
    'Warty Oreo',
    'Eastern Box Turtle',
    'Mediterranean Spur-Thighed Tortoise',
    'Human',
    'European Pond Turtle',
    'Beluga Sturgeon',
    'Rasphead Rockfish',
    'Tiger Rockfish',
    'Shortspine Thornyhead',
    'Stablefish',
    'Fin Whale',
    'Bigmouth Buffalo',
    'Blue Whale',
    'Redbanded Rockfish',
    'Northern Quahog',
    'Northern Propellerclam',
    'Telescope Cardinal',
    'White Sturgeon',
    'Olm',
    'American Lobster',
    'Yangtze Sturgeon',
    'European Sturgeon',
    'Pacific Ocean Perch',
    'Black Oreo',
    'Spiky Oreo',
    'Smooth Oreo',
    'Yellowmouth Rockfish',
    'Humpback Whale',
    'Quillback Rockfish',
    'Killer Whale',
    'Tuatara',
    'Atlantic Halibut',
    'European Eel',
    'Rosethorn Rockfish',
    'Australian Lungfish',
    'Beaked Whale',
    'Splitnose Rockfish',
    'Canary Rockfish',
    'Pink Cockatoo',
    'Silvergray Rockfish',
    'Andean Condor',
    'China Rockfish',
    'Gray Whale',
    'Sperm Whale',
    'American Alligator',
    'Loggerhead Sea Turtle',
    'Blandings Turtle',
    'Shortnose Spurdog',
    'Giant Sea Bass',
    'Spur Dogfish',
    'Green Sea Turtle',
    'Deepwater Redfish',
    'Sei Whale',
    'Roughscale Rattail',
    'Dugong',
    'Brydes Whale',
    'Alligator Snapping Turtle',
    'Leafscale Gulper Shark',
    'Southern Ground Hornbill',
    'Laysan Albatross',
    'West Indian Manatee',
    'Eurasian Eagle-Owl',
    'Shortnose Sturgeon',
    'North Atlantic Right Whale',
    'Dusky Rockfish',
    'Darkblotched Rockfish',
    'Salmon-Crested Cockatoo',
    'Chinese Alligator',
    'Yellowtail Rockfish',
    'Short-Finned Pilot Whale',
    'Desert Tortoise',
    'False Killer Whale',
    'Cuviers Beaked Whale',
    'Komodo Dragon'
]